[versions]
android-gradle-plugin = "8.13.2"
smile-android-sdk = "11.1.6"
androidx-activity = "1.11.0"
androidx-core = "1.17.0"
kotlin = "2.3.0"
ksp = "2.3.4"
junit = "4.13.2"
androidx-test-espresso = "3.7.0"
androidx-test-junit = "1.3.0"
compose-lint-checks = "1.4.2"
androidx-compose-bom = "2025.11.00"
ktlint-plugin = "14.0.1"
moshix = "0.34.1"
kotlin-immutable-collections = "0.4.0"
leakcanary = "2.14"
chucker = "4.2.0"
timber = "5.0.1"
datastore = "1.1.7"
androidx-core-splashscreen = "1.2.0"
androidx-fragment = "1.8.9"
androidx-lifecycle = "2.9.4"
androidx-navigation = "2.9.6"
mlkit-code-scanner = "16.1.0"
coroutines = "1.10.2"

[libraries]
smile-android-sdk = { module = "com.smileidentity:android-sdk", version.ref = "smile-android-sdk" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material-icons = { module = "androidx.compose.material:material-icons-core" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
compose-lint-checks = { module = "com.slack.lint.compose:compose-lint-checks", version.ref = "compose-lint-checks" }
datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
chucker = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
chucker-noop = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-immutable-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlin-immutable-collections" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
leakcanary-noop = { module = "com.squareup.leakcanary:leakcanary-android-release", version.ref = "leakcanary" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
mlkit-code-scanner = { module = "com.google.android.gms:play-services-code-scanner", version.ref = "mlkit-code-scanner"}
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }
moshix = { id = "dev.zacsweers.moshix", version.ref = "moshix" }
parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }

